<?php get_header(); ?>
<div style="height: 8rem;"></div>
    <div class="top_title_container">
      <div class="title_container">
        <h1>事業内容<span>Business</span></h1>
        <p>
          商品販売・製造・物流・事業開発まで、一貫して伴走サポートいたします。
        </p>
      </div>
    </div>
    <div class="business_intro_card fadein hover_three">
      <div class="business_intro_left">
        <h2>食を起点に、価値創造・事業成長を支えるパートナー</h2>
        <p>
          JIT(JAPAN INTER TRADING) は、<br>
          食を中心に、流通、ウェルネス、事業開発までを手がける<br>
          グローバルに事業を展開する商社です。
        </p>
        <p>
          世界に広がるネットワークと情報を活かし、<br>
          商品企画・調達から、物流、販売支援、事業構築まで、<br>
          各プロセスを一貫してサポートしています。
        </p>
        <p>
          食料、流通、ウェルネス、コーポレートディベロップメントなど<br>
          各分野において、多様な商品の取り扱いを行うとともに、<br>
          それを支えるロジスティクスや品質管理の体制構築、<br>
          さらには国際的なプロジェクトや事業開発の支援まで、<br>
          幅広いサービスを提供しています。
        </p>
        <p>
          企業規模や業界を問わず、<br>
          それぞれのパートナーが持つ伝統、強みや課題に向き合いながら<br>
          持続的な価値創造と事業成長を通して共存・共栄することを<br>
          大切にしています。
        </p>
        <span id="business-core"></span>
      </div>
      <div class="business_intro_right">
        <ul>
          <li><i class="fa-solid fa-check"></i> 世界各国の食品・飲料・原料の輸入・販売及びマーケティング</li>
          <li><i class="fa-solid fa-check"></i> 日本発ブランドの海外展開、現地市場での展開・販売支援及び<br>マーケティング</li>
          <li><i class="fa-solid fa-check"></i> ODM / OEM を含む商品企画・開発の支援</li>
          <li><i class="fa-solid fa-check"></i> ロジスティクス設計、品質管理、流通体制の構築支援</li>
          <li><i class="fa-solid fa-check"></i> 国際プロジェクトおよび事業開発に関する支援</li>
        </ul>
      </div>
    </div>
    
    <section class="business_card_section fadein">
      
      <div class="title_container">
        <h1>事業領域<span>Core Business</span></h1>
        <p>輸入・輸出・販売促進・事業開発を軸に、事業成長をワンストップで支える。</p>
      </div>
      <div class="business_card_container">
        <div class="business_card hover_three">
          <div class="business_label">EXPORT</div>
          <h3>輸出事業</h3>
          <p class="business_subtitle">日本の強みと伝統・革新を、世界の市場へ。</p>
          <p class="business_lead">
            日本製の食品・日用品を中心に、<br>
            アジア・中東、欧米など海外市場へ展開しています。<br><br>
            現地ニーズを踏まえた商品提案から、<br>
            ラベル・仕様のローカライズ、<br>
            海外パートナーとの協業による販路開拓まで、<br>
            長期的な市場定着を見据えた輸出を支援します。<br><br>
          </p>
          <p class="business_subtitle">主な取り組み</p>
          <ul>
            <li>現地ニーズに合わせた商品提案</li>
            <li>ラベル・仕様のローカライズ対応</li>
            <li>海外パートナーとの共同プロモーション</li>
            <li>継続的な取引を見据えた販路設計</li>
          </ul>
        </div>
        <div class="business_card hover_three">
          <div class="business_label">IMPORT</div>
          <h3>輸入事業</h3>
          <p class="business_subtitle">世界の価値を見極め、日本市場へつなぐ。</p>
          <p class="business_lead">
            アジア・欧州を中心に、<br>
            世界各地の食品・飲料・原料を日本市場へ届けています。<br><br>
            海外メーカーとの直接取引を通じ、<br>
            商品選定から条件調整、品質・表示・法令確認、<br>
            輸入通関、在庫・物流の最適化まで、<br>
            安心・透明性を重視した輸入体制を構築します。<br><br>
          </p>
          <p class="business_subtitle">主な取り組み</p>
          <ul>
            <li>海外メーカーとの直接取引・条件調整</li>
            <li>ODM / OEM を含む商品企画・開発支援</li>
            <li>品質・表示・法令チェック</li>
            <li>輸入通関・在庫・物流の最適化</li>
          </ul>
        </div>
        <div class="business_card hover_three">
          <div class="business_label">PROMOTION & SUPPORT</div>
          <h3>販売促進・事業サポート</h3>
          <p class="business_subtitle">「取引して終わり」にしない、成長支援。</p>
          <p class="business_lead">
            商品が市場に届いたその先まで。<br>
            試食会やキャンペーンなどの店頭施策、<br>
            売場レイアウト・陳列提案、<br>
            SNSやデジタルを活用した情報発信を通じて、<br>
            販売の現場を支援します。<br><br>
            販売データをもとにした改善提案を行い、<br>
            取引先とともに、持続的な事業成長を目指します。<br><br>
          </p>
          <p class="business_subtitle">主な取り組み</p>
          <ul>
            <li>試食会・キャンペーンなどの店頭プロモーション</li>
            <li>売場レイアウト・陳列提案</li>
            <li>SNS / デジタルを活用した情報発信</li>
            <li>販売データをもとにした改善提案</li>
          </ul>
        </div>
      </div>
    </section>
    <!-- Global Network -->
    <section class="global_network_section fadein" id="business-network">
      <div class="title_container">
        <h1>グローバルネットワーク<span class="globalnetwork">Global Network</span></h1>
        <p>日本を起点に、アジア・中東、欧米へとネットワークを拡大しております。</p>
      </div>

      <div class="global_map_container hover_three">
        <div class="trade-map" id="tradeMap">
          <div class="trade-map-text-wrapper">
            <p class="trade-map-text">世界を巡り、価値を見つけ、次の市場へつなぐ。</p>
            <p class="trade-map-text-en">Exploring, Connecting, Growing Through Value</p>
          </div>
          <img src="<?php echo get_template_directory_uri(); ?>/img/trade.jpg" alt="世界ネットワーク" class="global_map">

          <!-- Hotspots are dynamically generated by JavaScript -->

          <!-- Card -->
          <div class="port-card" id="portCard" aria-hidden="true">
            <button class="port-close" id="portClose" aria-label="閉じる">×</button>

            <div class="port-head">
              <p class="port-title" id="portTitle">Europe</p>
              <p class="port-sub">Trade Log</p>
            </div>

            <!-- Countries -->
            <div class="port-countries" id="portCountries"></div>

            <div class="port-cols">
              <div class="port-col">
                <p class="port-col-title">輸入商品</p>
                <ul class="port-list" id="importList"></ul>
              </div>
              <div class="port-col">
                <p class="port-col-title">輸出商品</p>
                <ul class="port-list" id="exportList"></ul>
              </div>
            </div>
          </div>

          <div class="map-backdrop" id="mapBackdrop" aria-hidden="true"></div>
        </div>
      </div>

      <p class="global_caption">※取扱国やエリアは、お取引状況に応じて随時拡大しています。</p>
    </section>
    <!-- ===== Flow ===== -->
         <!-- ===== Upstream → Downstream：食のバリューチェーン ===== -->
    <div class="business_chain_wrapper">
    <section class="business_bridge_section fadein">
      <div class="title_container">
        <h1>バリューチェーン<span>Value Chain</span></h1>
        <p>
          「どこからどこまでお願いできるの？」というお客様にも、<br>
          生産者から生活者までの流れがひと目でイメージできるよう、JAPAN INTER TRADING が担う役割を整理しました。
        </p>
      </div>

      <div class="bridge_panel">

        <!-- ▼ 輸入フロー -->
        <div class="bridge_row">
          <div class="bridge_row_title">
            <span class="bridge_row_main">輸入（Import）</span>
            <span class="bridge_row_sub">海外から日本の食卓へ</span>
          </div>

          <div class="bridge_flow">
            <div class="bridge_node hover_three">
              <div class="bridge_icon"><i class="fa-solid fa-industry"></i></div>
              <div class="bridge_node_title">海外メーカー</div>
              <div class="bridge_node_text">現地の食品・飲料・畜産メーカー</div>
            </div>

            <div class="bridge_arrow"><i class="fa-solid fa-angles-right"></i></div>

            <div class="bridge_node hover_three">
              <div class="bridge_icon"><i class="fa-solid fa-warehouse"></i></div>
              <div class="bridge_node_title">集荷・現地倉庫</div>
              <div class="bridge_node_text">ロットをまとめて出荷準備</div>
            </div>

            <div class="bridge_arrow"><i class="fa-solid fa-angles-right"></i></div>

            <div class="bridge_node hover_three">
              <div class="bridge_icon"><i class="fa-solid fa-ship"></i></div>
              <div class="bridge_node_title">国際輸送</div>
              <div class="bridge_node_text">船・飛行機で日本へ輸送</div>
            </div>

            <div class="bridge_arrow"><i class="fa-solid fa-angles-right"></i></div>

            <div class="bridge_node hover_three">
              <div class="bridge_icon"><i class="fa-solid fa-clipboard-check"></i></div>
              <div class="bridge_node_title">通関・検品</div>
              <div class="bridge_node_text">書類・品質・表示をチェック</div>
            </div>

            <div class="bridge_arrow"><i class="fa-solid fa-angles-right"></i></div>

            <div class="bridge_node hover_three">
              <div class="bridge_icon"><i class="fa-solid fa-store"></i></div>
              <div class="bridge_node_title">小売・外食・EC</div>
              <div class="bridge_node_text">店頭・オンラインで生活者へ</div>
            </div>
          </div>
        </div>

        <!-- ▼ 輸出・外国間フロー -->
        <div class="bridge_row">
          <div class="bridge_row_title">
            <span class="bridge_row_main">輸出・外国間（Export / Triangle）</span>
            <span class="bridge_row_sub">日本発ブランドや三国間にも対応</span>
          </div>

          <div class="bridge_flow">
            <div class="bridge_node hover_three">
              <div class="bridge_icon"><i class="fa-solid fa-industry"></i></div>
              <div class="bridge_node_title">日本・海外のメーカー</div>
              <div class="bridge_node_text">輸出・三国間の起点となるメーカー</div>
            </div>

            <div class="bridge_arrow"><i class="fa-solid fa-angles-right"></i></div>

            <div class="bridge_node hover_three">
              <div class="bridge_icon"><i class="fa-solid fa-diagram-project"></i></div>
              <div class="bridge_node_title">スキーム設計</div>
              <div class="bridge_node_text">条件や通関・規制に合わせて個別設計</div>
            </div>

            <div class="bridge_arrow"><i class="fa-solid fa-angles-right"></i></div>

            <div class="bridge_node hover_three">
              <div class="bridge_icon"><i class="fa-solid fa-plane-departure"></i></div>
              <div class="bridge_node_title">国際輸送</div>
              <div class="bridge_node_text">現地パートナー・倉庫へ配送</div>
            </div>

            <div class="bridge_arrow"><i class="fa-solid fa-angles-right"></i></div>

            <div class="bridge_node hover_three">
              <div class="bridge_icon"><i class="fa-solid fa-handshake"></i></div>
              <div class="bridge_node_title">現地パートナー</div>
              <div class="bridge_node_text">卸・ディストリビューターなど</div>
            </div>

            <div class="bridge_arrow"><i class="fa-solid fa-angles-right"></i></div>

            <div class="bridge_node hover_three">
              <div class="bridge_icon"><i class="fa-solid fa-store"></i></div>
              <div class="bridge_node_title">現地の生活者</div>
              <div class="bridge_node_text">現地小売・外食・EC で展開</div>
            </div>
          </div>
        </div>

        <p class="bridge_note">
          ※ 上記は一例です。実際には、商流・物流・条件に応じてスキームを個別に設計し、<br class="pc_only">
          「どこからどこまでお願いできるか」をご相談内容に合わせて柔軟に対応いたします。
        </p>
      </div>
      <p id="business-flow"></p>
    </section>

    <section class="business_value_support_section fadein">
      <div class="title_container">
        <h1>JIT Value Support<span>価値創造・成長支援（横断機能）</span></h1>
        <p>
          JIT（JAPAN INTER TRADING）は、
          輸入・輸出・三国間取引といった商流・物流の実行に加え、<br>
          以下の機能を横断的に担うことで、
          取引先の持続的な価値創造と事業成長を支援します。
        </p>
      </div>

      <div class="value_support_container">
        <div class="value_support_item">
          <div class="value_support_content">
            <div class="value_support_label">Supply Chain Design</div>
            <h3>サプライチェーン設計・最適化</h3>
            <p>
              物流、在庫、輸送手段、リードタイム、コストのバランスを考慮し、
              商流全体を見渡したサプライチェーンの設計・最適化を行います。<br><br>
              安定供給と効率性の両立を図り、
              事業の継続性と競争力の向上を支えます。
            </p>
          </div>
        </div>

        <div class="value_support_item">
          <div class="value_support_content">
            <div class="value_support_label">Marketing & Sales Support</div>
            <h3>マーケティング・販売支援</h3>
            <p>
              市場や顧客ニーズを踏まえた商品提案に加え、
              売場づくり、販促施策、デジタルを活用した情報発信などを通じて、
              商品が市場に定着し、継続的に選ばれる仕組みを支援します。
            </p>
          </div>
        </div>

        <div class="value_support_item">
          <div class="value_support_content">
            <div class="value_support_label">Business Design & Development</div>
            <h3>事業設計・事業開発支援</h3>
            <p>
              商流・物流・販売チャネルを組み合わせ、
              取引条件や市場特性に応じた事業スキームを設計します。<br><br>
              新規市場や新たなチャネルへの展開を含め、
              中長期的な視点で事業の成長と発展を支援します。
            </p>
          </div>
        </div>

        <div class="value_support_item">
          <div class="value_support_content">
            <div class="value_support_label">Quality & Compliance</div>
            <h3>品質管理・法令対応</h3>
            <p>
              品質基準の確認、表示・法令のチェック、
              各国規制への対応などを通じて、
              安心・安全な商品提供とリスク管理を支えます。<br><br>
              透明性の高い体制構築により、
              取引先との信頼関係を大切にしています。
            </p>
          </div>
        </div>

        <div class="value_support_item">
          <div class="value_support_content">
            <div class="value_support_label">Capital & Strategic Alliance Support</div>
            <h3>資本・アライアンス支援（投資・共創）</h3>
            <p>
              事業の成長段階や課題に応じて、
              出資、株式の持ち合い、業務資本提携、M&A など、
              資本面での関与を含めた支援を行います。<br><br>
              金融的な投資を目的とするものではなく、
              事業の実行と成長を前提とした事業投資を行います。<br><br>
              事業運営に寄り添いながら、
              事業価値の向上と中長期的な成長をともに目指します。
            </p>
          </div>
        </div>

        <div class="value_support_item">
          <div class="value_support_content">
            <div class="value_support_label">Business Renewal & Transformation Support</div>
            <h3>事業再生・構造転換支援</h3>
            <p>
              市場環境や事業構造の変化に直面する企業に対し、
              事業の再設計、サプライチェーンの見直し、
              パートナー連携や資本構成の最適化を通じて、
              事業再生や次の成長フェーズへの移行を支援します。<br><br>
              既存の強みを活かしながら、
              持続可能な事業モデルへの転換を目指します。
            </p>
          </div>
        </div>
      </div>
    </section>
    </div>

    <section class="business_flow_section fadein">
      <div class="title_container">
        <h1>お取引の流れ<span>Flow</span></h1>
        <p>課題のヒアリングから商品・事業スキームの提案、納品、そしてその後の改善・フォローまで、事業に寄り添いながら一貫して伴走します。</p>
      </div>

      <div class="flow_step_container">
        <div class="flow_step hover_three">
          <div class="flow_number">01</div>
          <h3>ヒアリング</h3>
          <p>ターゲット・販売チャネル・ご予算などを伺い、事業課題や目的を整理します。</p>
        </div>
        <div class="flow_step hover_three">
          <div class="flow_number">02</div>
          <h3>商品・スキーム提案</h3>
          <p>輸入 / 輸出 / OEM など市場や条件に応じた最適な商品・事業スキームをご提案します。</p>
        </div>
        <div class="flow_step hover_three">
          <div class="flow_number">03</div>
          <h3>条件調整・契約</h3>
          <p>数量・価格・納期・物流などの条件を詰め、契約を締結します。</p>
        </div>
        <div class="flow_step hover_three">
          <div class="flow_number">04</div>
          <h3>手配・納品</h3>
          <p>製造・輸送・通関・納品までを一括で管理し、安全にお届けします。</p>
        </div>
        <div class="flow_step hover_three">
          <div class="flow_number">05</div>
          <h3>販売フォロー</h3>
          <p>販売状況を踏まえ、改善提案やプロモーション支援を通じて、継続的な事業成長をサポートします。</p>
        </div>
      </div>
    </section>
      <div class="business_cta_inner fadein ">
        <h2>海外展開・商品開発のパートナーをお探しの企業様へ</h2>
        <p>
          「まずは相談だけしたい」「具体的な案件について聞いてみたい」など、<br>
          小さなことでもお気軽にお問い合わせください。
        </p>
        <a href="<?php echo home_url('/contact'); ?>" class="business_cta_button">お問い合せフォームへ</a>
      </div>
<?php get_footer(); ?>